# Generated by Django 4.0.4 on 2022-06-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviez', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
